spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demos
  flyway:
    locations: classpath:db/migration
# spring.flyway.locations=classpath:db/migration
#  spring.datasource.url=jdbc:postgresql://<HOST>:<PORT>/<DATABASE_NAME>
#  spring.datasource.username=<YOUR_USERNAME>
#  spring.datasource.password=<YOUR_PASSWORD>